name: Crosspost

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "source/**/**/*.md"
      - "posts/*"
  workflow_dispatch:

jobs:
  publish:
    name: Publish Blog Post
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: blogpub
        uses: protiumx/blogpub@v0.8.0
        with:
          articles_folder: "posts"
          devto_api_key: ${{ secrets.DEVTO_API_KEY }}
          gh_token: ${{ secrets.GH_TOKEN }}
          medium_token: ${{ secrets.MEDIUM_TOKEN }}
          medium_user_id: ${{ secrets.MEDIUM_USER_ID }}
          medium_base_url: "https://api.medium.com/v1"
